modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
[[mods]]
modId = "aoainfo"
version = "${file.jarVersion}"
displayName = "Extra AoA Info"
logoFile="logo.png"
displayURL="https://adventofascension.gamepedia.com/Advent_of_Ascension_Wiki"
credits="Tslat - original mod (AoA InfoBundle)"
authors = "Shimizu_Izumi"
description = '''
Adds more information to areas of Advent of Ascension
'''
[[dependencies.aoainfo]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.aoainfo]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
[[dependencies.aoainfo]]
modId = "aoa3"
mandatory = true
versionRange = "[3.6.18,)"
ordering = "BEFORE"
side = "CLIENT"
